//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightInScope", ReplyAction="http://tempuri.org/IService1/getFlightInScopeResponse")]
        string getFlightInScope(string cityFrom, string cityTo, int scope);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightInScope", ReplyAction="http://tempuri.org/IService1/getFlightInScopeResponse")]
        System.Threading.Tasks.Task<string> getFlightInScopeAsync(string cityFrom, string cityTo, int scope);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllFlights", ReplyAction="http://tempuri.org/IService1/getAllFlightsResponse")]
        string getAllFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllFlights", ReplyAction="http://tempuri.org/IService1/getAllFlightsResponse")]
        System.Threading.Tasks.Task<string> getAllFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightsFromTo", ReplyAction="http://tempuri.org/IService1/getFlightsFromToResponse")]
        string getFlightsFromTo(string cityFrom, string cityTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightsFromTo", ReplyAction="http://tempuri.org/IService1/getFlightsFromToResponse")]
        System.Threading.Tasks.Task<string> getFlightsFromToAsync(string cityFrom, string cityTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCitiesTo", ReplyAction="http://tempuri.org/IService1/getCitiesToResponse")]
        string[] getCitiesTo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCitiesTo", ReplyAction="http://tempuri.org/IService1/getCitiesToResponse")]
        System.Threading.Tasks.Task<string[]> getCitiesToAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCitiesFrom", ReplyAction="http://tempuri.org/IService1/getCitiesFromResponse")]
        string[] getCitiesFrom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCitiesFrom", ReplyAction="http://tempuri.org/IService1/getCitiesFromResponse")]
        System.Threading.Tasks.Task<string[]> getCitiesFromAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getFlightInScope(string cityFrom, string cityTo, int scope) {
            return base.Channel.getFlightInScope(cityFrom, cityTo, scope);
        }
        
        public System.Threading.Tasks.Task<string> getFlightInScopeAsync(string cityFrom, string cityTo, int scope) {
            return base.Channel.getFlightInScopeAsync(cityFrom, cityTo, scope);
        }
        
        public string getAllFlights() {
            return base.Channel.getAllFlights();
        }
        
        public System.Threading.Tasks.Task<string> getAllFlightsAsync() {
            return base.Channel.getAllFlightsAsync();
        }
        
        public string getFlightsFromTo(string cityFrom, string cityTo) {
            return base.Channel.getFlightsFromTo(cityFrom, cityTo);
        }
        
        public System.Threading.Tasks.Task<string> getFlightsFromToAsync(string cityFrom, string cityTo) {
            return base.Channel.getFlightsFromToAsync(cityFrom, cityTo);
        }
        
        public string[] getCitiesTo() {
            return base.Channel.getCitiesTo();
        }
        
        public System.Threading.Tasks.Task<string[]> getCitiesToAsync() {
            return base.Channel.getCitiesToAsync();
        }
        
        public string[] getCitiesFrom() {
            return base.Channel.getCitiesFrom();
        }
        
        public System.Threading.Tasks.Task<string[]> getCitiesFromAsync() {
            return base.Channel.getCitiesFromAsync();
        }
    }
}
