//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightInScope", ReplyAction="http://tempuri.org/IService1/getFlightInScopeResponse")]
        string getFlightInScope(string cityFrom, string cityTo, int scopeFrom, int scopeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFlightInScope", ReplyAction="http://tempuri.org/IService1/getFlightInScopeResponse")]
        System.Threading.Tasks.Task<string> getFlightInScopeAsync(string cityFrom, string cityTo, int scopeFrom, int scopeTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getFlightInScope(string cityFrom, string cityTo, int scopeFrom, int scopeTo) {
            return base.Channel.getFlightInScope(cityFrom, cityTo, scopeFrom, scopeTo);
        }
        
        public System.Threading.Tasks.Task<string> getFlightInScopeAsync(string cityFrom, string cityTo, int scopeFrom, int scopeTo) {
            return base.Channel.getFlightInScopeAsync(cityFrom, cityTo, scopeFrom, scopeTo);
        }
    }
}
